### ISSUE TITLE
Add tests and documentation for elasticsearch log reader PR

### ISSUE THREAD

**Issue by schnie** [astronomer/airflow#38]
This is already merged to our fork and being used in production. We should write tests and docs to compliment the code in this PR https://github.com/astronomer/airflow/pull/37/files

**Comment by schnie** [comment]
Will hopefully have a clearer picture of airflow testing after call with @ashb next week.

**Comment by andriisoldatenko** [comment]
https://github.com/apache/airflow/pull/4303

**Comment by schnie** [comment]
@andriisoldatenko that PR didn't work out in the end and I took a stab at rewriting it with the PR mentioned above. We should probably close the old one and open a new one, once we have the docs updated and some tests.

**Comment by schnie** [comment]
This is being tracked here: https://github.com/apache/airflow/pull/5048
