### ISSUE TITLE
Prepare KubernetesExecutor PR

### ISSUE THREAD

**Issue by schnie** [astronomer/airflow#39]
Prepare PR (docs / tests?) for this commit: https://github.com/astronomer/airflow/commit/8b9ef97082bcb0750243a605926e654e3fe80469

This adds support for passing in a dictionary of extra labels to append to each pod launched by the kubernetes executor.

**Comment by andriisoldatenko** [comment]
I've created ticket:
https://issues.apache.org/jira/browse/AIRFLOW-4159
from @ashb: possibly already eixsts https://issues.apache.org/jira/browse/AIRFLOW-3649
Oh and has a PR https://github.com/apache/airflow/pull/4459

**Comment by andriisoldatenko** [comment]
@schnie let's close via https://github.com/apache/airflow/commit/e4bf4879e17051066b5244510d8757463f971d97
