### ISSUE TITLE
Airflow scheduler stops when Kubernetes Quota is exceeded

### ISSUE THREAD

**Issue by schnie** [astronomer/airflow#40]
Right now, if a scheduler running the `KubernetesExecutor` attempts to schedule a pod into a namespace that would put it over a resource quota, the scheduler logs the error, then quits scheduling tasks. The scheduler does not crash or anything, just stops scheduling.

Seems like we need a way to more gracefully deal with situation.

**Comment by schnie** [comment]
@ashb any thoughts on the behavior here? I believe the exception gets thrown here: https://github.com/apache/airflow/blob/master/airflow/contrib/kubernetes/pod_launcher.py#L59.

I'm not sure if there's a more specific exception we could look for and handle differently or not.

**Comment by andriisoldatenko** [comment]
@ashb @schnie 
This bug has been fixed using [pull/3960](https://github.com/apache/airflow/pull/3960/files#diff-b1d8d65aeaa7d031dfe5b197d6c5aa69R602) and released in `1.10.3` [CHANGELOG.txt#L181 ](https://github.com/apache/airflow/blob/master/CHANGELOG.txt#L181)

Issue in Jira: [https://issues.apache.org/jira/browse/AIRFLOW-2966](AIRFLOW-2966)

I checked status of fork and tag: 
https://github.com/astronomer/airflow/blob/v1-10-2/airflow/contrib/executors/kubernetes_executor.py#L651-L653 we don't have this change on production.

Regarding `PodOperator` - i think behavior is looks correct.

Please let me know what to do next.

**Comment by andriisoldatenko** [comment]
@schnie 
I think we can close it after releasing https://github.com/astronomer/airflow/tree/v1-10-3
